ACodec: Fix video autoscaling on old OMX decoders
On Android N video autoscaling will cause the video to zoom in, being mostly outside of the frame of the video.
This is because android no longer tries to match output ports before putting the new resolution in effect.
Exynos OMX decoders send a message to get the new output crop, but it's lost along the way.
Similarly to how Android M handles it, send the format change right before transitioning to ExecutingState.

* forward port to android 8.1.x
* fixup

frameworks/av/media/libstagefright/ACodec.cpp:7896: error: undefined reference to 'android::ACodec::addKeyFormatChangesToRenderBufferNotification(android::sp<android::AMessage>&)'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Signed-off-by: vishalk17 <vishalkapadi95@gmail.com>

Change-Id: I19f974d37f9b11161efc7ee470301f444691fde6